name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.0
      # Install dependencies
      - run: npm install
      # Transform Figma Tokens JSON to something Style Dictionary can read
      - run: npx token-transformer tokens.json tokens/global.json global
      # Create a rvca theme, exclude the global tokens
      # - run: npx token-transformer tokens.json tokens/typography-rvca.json global,typography-rvca global
      - run: npx token-transformer tokens.json tokens/rvca.json global,typography-rvca,rvca global
      # Create a qs theme, exclude the global tokens
      #- run: npx token-transformer tokens.json tokens/typography-qs.json global,typography-qs global
      - run: npx token-transformer tokens.json tokens/qs.json global,typography-qs,qs global
      # Convert tokens according to Style Dictionary config
      - run: node build.js
      # Add files that were created during a run, e.g. created files from style dictionary or token-transformer.
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Tokens
