name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.0
      # Install dependencies
      - run: npm install
      # Transform Figma Tokens JSON to something Style Dictionary can read
      - run: npx token-transformer tokens.json tokens/global.json global
      # Create main theme, exclude the global tokens
      # - run: npx token-transformer tokens.json tokens/rvca.json global,typography-rvca,rvca global
      # - run: npx token-transformer tokens.json tokens/semantic.json core,semantic core,comp
      # - run: npx token-transformer tokens.json tokens/comp.json core,semantic,comp core,semantic
       # Create brand themes theme, exclude the global tokens
      # - run: npx token-transformer tokens.json tokens/billabong.json core,semantic,comp,billabong core,semantic,comp
      # - run: npx token-transformer tokens.json tokens/dc-shoes.json core,semantic,comp,dc-shoes core,semantic,comp
      # - run: npx token-transformer tokens.json tokens/qs.json core,semantic,comp,qs core,semantic,comp
      # - run: npx token-transformer tokens.json tokens/roxy.json core,semantic,comp,roxy core,semantic,comp
      # - run: npx token-transformer tokens.json tokens/rvca.json core,semantic,comp,rvca core,semantic,comp

      - run: npx token-transformer tokens.json tokens/billabong.json core,semantic,comp,billabong core,comp
      - run: npx token-transformer tokens.json tokens/dc-shoes.json core,semantic,comp,dc-shoes core,comp
      - run: npx token-transformer tokens.json tokens/qs.json core,semantic,comp,qs core,comp
      - run: npx token-transformer tokens.json tokens/roxy.json core,semantic,comp,roxy core,comp
      - run: npx token-transformer tokens.json tokens/rvca.json core,semantic,comp,rvca core,comp

      # Convert tokens according to Style Dictionary config
      - run: node build.js
      # Add files that were created during a run, e.g. created files from style dictionary or token-transformer.
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Tokens
